---
name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.4.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          LINTER_RULES_PATH: codestyle
          JAVA_FILE_NAME: custom-google-checks.xml
          SAVE_SUPER_LINTER_SUMMARY: true
          SAVE_SUPER_LINTER_OUTPUT: true
          IGNORE_GITIGNORED_FILES: true

      - name: Post artifact
        if: always()
        uses: actions/upload-artifact@v4.5.0
        with:
          name: lint results
          path: ${{ github.workspace }}/super-linter-output/super-linter-summary.md
